# This workflow will apply github actions for golang project

name: Go

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  checks: write
  contents: write
jobs:

  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Install golint
      run: |
        go install golang.org/x/lint/golint@latest
        export PATH=$PATH:$(go env GOPATH)/bin

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Format
      run: |
        go version
        go fmt ./...

    - name: Linter
      run: golint ./...